[package]
name = "git-varro"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "git-varro"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.28"
git2 = "0.20"
indicatif = "0.17"
ratatui = "0.29"
rayon = "1.10"
varro = { git = "https://github.com/shaneikennedy/varro", branch = "master", package = "varro" }
